from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("reflexio-ai")
except PackageNotFoundError:
    __version__ = "0.0.0-dev"

from reflexio.models.api_schema.retriever_schema import (
    ConversationTurn,
    GetAgentPlaybooksViewResponse,
    GetEvaluationResultsViewResponse,
    GetInteractionsViewResponse,
    GetProfilesViewResponse,
    GetRequestsViewResponse,
    GetUserPlaybooksViewResponse,
    ProfileChangeLogViewResponse,
    RequestDataView,
    SearchAgentPlaybooksViewResponse,
    SearchInteractionRequest,
    SearchInteractionResponse,
    SearchInteractionsViewResponse,
    SearchProfilesViewResponse,
    SearchUserPlaybooksViewResponse,
    SearchUserProfileRequest,
    SearchUserProfileResponse,
    SessionView,
    UnifiedSearchViewResponse,
)
from reflexio.models.api_schema.service_schemas import (
    AddUserPlaybookRequest,
    AddUserPlaybookResponse,
    AgentPlaybook,
    BlockingIssue,
    BlockingIssueKind,
    BulkDeleteResponse,
    DeleteAgentPlaybooksByIdsRequest,
    DeleteProfilesByIdsRequest,
    DeleteRequestsByIdsRequest,
    DeleteUserInteractionRequest,
    DeleteUserInteractionResponse,
    DeleteUserPlaybooksByIdsRequest,
    DeleteUserProfileRequest,
    DeleteUserProfileResponse,
    Interaction,
    InteractionData,
    PlaybookStatus,
    ProfileTimeToLive,
    PublishUserInteractionRequest,
    PublishUserInteractionResponse,
    RerunPlaybookGenerationRequest,
    RerunPlaybookGenerationResponse,
    RerunProfileGenerationRequest,
    RerunProfileGenerationResponse,
    Status,
    ToolUsed,
    UserActionType,
    UserPlaybook,
    UserProfile,
)
from reflexio.models.api_schema.ui.entities import (
    AgentPlaybookView,
    EvaluationResultView,
    InteractionView,
    ProfileChangeLogView,
    ProfileView,
    UserPlaybookView,
)
from reflexio.models.config_schema import (
    AgentSuccessConfig,
    Config,
    PlaybookAggregatorConfig,
    PlaybookConfig,
    ProfileExtractorConfig,
    StorageConfig,
    StorageConfigDisk,
    StorageConfigSQLite,
    StorageConfigSupabase,
    StorageConfigTest,
    ToolUseConfig,
)

from .client import ReflexioClient

debug = False
log = None  # Set to either 'debug' or 'info', controls console logging


__all__ = [
    "__version__",
    "ReflexioClient",
    # Data models (internal, with embeddings)
    "UserActionType",
    "ProfileTimeToLive",
    "InteractionData",
    "Interaction",
    "UserProfile",
    "AgentPlaybook",
    "UserPlaybook",
    "BlockingIssue",
    "BlockingIssueKind",
    "ToolUsed",
    "Status",
    "PlaybookStatus",
    # View models (user-facing, without embeddings)
    "InteractionView",
    "ProfileView",
    "UserPlaybookView",
    "AgentPlaybookView",
    "EvaluationResultView",
    "ProfileChangeLogView",
    # Request types
    "PublishUserInteractionRequest",
    "DeleteUserProfileRequest",
    "DeleteUserInteractionRequest",
    "AddUserPlaybookRequest",
    "RerunProfileGenerationRequest",
    "RerunPlaybookGenerationRequest",
    "ConversationTurn",
    "SearchInteractionRequest",
    "SearchUserProfileRequest",
    "DeleteRequestsByIdsRequest",
    "DeleteProfilesByIdsRequest",
    "DeleteAgentPlaybooksByIdsRequest",
    "DeleteUserPlaybooksByIdsRequest",
    # Response types (internal)
    "PublishUserInteractionResponse",
    "DeleteUserProfileResponse",
    "DeleteUserInteractionResponse",
    "AddUserPlaybookResponse",
    "RerunProfileGenerationResponse",
    "RerunPlaybookGenerationResponse",
    "SearchInteractionResponse",
    "SearchUserProfileResponse",
    "BulkDeleteResponse",
    # View response types (user-facing)
    "GetInteractionsViewResponse",
    "GetProfilesViewResponse",
    "SearchInteractionsViewResponse",
    "SearchProfilesViewResponse",
    "GetEvaluationResultsViewResponse",
    "ProfileChangeLogViewResponse",
    "RequestDataView",
    "SessionView",
    "GetRequestsViewResponse",
    "UnifiedSearchViewResponse",
    "GetUserPlaybooksViewResponse",
    "GetAgentPlaybooksViewResponse",
    "SearchUserPlaybooksViewResponse",
    "SearchAgentPlaybooksViewResponse",
    # Config types
    "StorageConfigTest",
    "StorageConfigDisk",
    "StorageConfigSQLite",
    "StorageConfigSupabase",
    "StorageConfig",
    "ProfileExtractorConfig",
    "PlaybookAggregatorConfig",
    "PlaybookConfig",
    "AgentSuccessConfig",
    "ToolUseConfig",
    "Config",
]
